### ISSUE TITLE
fedorahosted.org links found

### ISSUE THREAD

**Issue by eherget** [ggainey/tracwiki2githubwiki#12]
PAGE: https://github.com/ggainey/spacewalk/wiki/Architecture
1) "PostgreSQL Database" in first paragraph
2) "here" at end of section titled "Frontend API"

PAGE: https://github.com/ggainey/spacewalk/wiki/BrainBox
1) "SRPM Sync" in section "Repo and RPM Handling"
2) "func"
3) "https://fedorahosted.org/spacewalk/wiki/KickstartScriptRevisioning"

PAGE: https://github.com/ggainey/spacewalk/wiki/BugHandling
1) "https://fedorahosted.org/spacewalk/wiki/ReleaseProcess"

PAGE: https://github.com/ggainey/spacewalk/wiki/CobblerKoanIntegration
1) "https://fedorahosted.org/cobbler"

**Comment by ggainey** [comment]
#10 will handle this, in conjunction with --trac-base
