### ISSUE TITLE
Concerning URL in link

### ISSUE THREAD

**Issue by eherget** [ggainey/tracwiki2githubwiki#15]
On this page https://github.com/ggainey/spacewalk/wiki/BrainBox

near the bottom of the page is a link for this text "The Architecture of Participation: ..." that goes here:

http://209.85.215.104/search?q=cache:0hNSibSYPmYJ:www.people.hbs.edu/cbaldwin/DR2/BaldwinArchPartAll.pdf+%22architecture+of+participation%22+harvard&hl=en&ct=clnk&cd=1&gl=us&client=firefox-a

Seeing the IP address scares me.  And it looks like it may ultimately get redirected to www.people.hbs.edu/cbaldwin/DR2/BaldwinArchPartAll.pdf

**Comment by ggainey** [comment]
It's in the base Trac content - not something the tool has control over
